language: c

sudo: required

service:
 - docker

## NOTIFICATIONS
notifications:
  email:
    recipients:
    - anthony.denin@epitech.eu
    on_success: never
    on_failure: always

before_install:
 - docker pull epitechcontent/epitest-docker

jobs:
  include :
    - stage: build
      name: "Build"
      if: branch != master
      script:
       - docker run -v $PWD:/app epitechcontent/epitest-docker bash -c "cd app && make && make fclean"

    - stage: tests
      name: "Unit Tests"
      depends on: build
      if: branch != master
      script:
       - docker run -v $PWD:/app epitechcontent/epitest-docker bash -c "cd app && make fclean && make tests_run"

    - stage: deploy
      name: "Deployement"
      if: branch = master AND type NOT IN (cron, pull_request)
      before_script:
       - ssh-keyscan git.epitech.eu >> ~/.ssh/known_hosts
       - git checkout master
      script:
       - git push --repo=git@git.epitech.eu:/anthony.denin@epitech.eu/PSU_minishell2_2019 --force
